# Generated by Django 4.2.10 on 2024-02-23 22:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Shipping to? Who is it for?",
                        max_length=120,
                        null=True,
                    ),
                ),
                (
                    "nickname",
                    models.CharField(
                        blank=True,
                        help_text="Internal Reference Nickname",
                        max_length=120,
                        null=True,
                    ),
                ),
                ("address_line_1", models.CharField(max_length=120)),
                (
                    "address_line_2",
                    models.CharField(blank=True, max_length=120, null=True),
                ),
                (
                    "country",
                    models.CharField(
                        default="RU",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$",
                                "Only uppercase letters and length has be 2",
                            )
                        ],
                    ),
                ),
                ("state", models.CharField(max_length=120)),
                ("city", models.CharField(max_length=120)),
                ("postal_code", models.CharField(max_length=120)),
                (
                    "billing_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="billing.billingprofile",
                    ),
                ),
            ],
        ),
    ]
