# Generated by Django 4.2.10 on 2024-03-11 23:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("addresses", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="city",
            field=models.CharField(default="Porto", max_length=120),
        ),
        migrations.AlterField(
            model_name="address",
            name="country",
            field=models.CharField(
                default="PT",
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}$", "Only uppercase letters and length has be 2"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(default="000-000", max_length=120),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(default="Porto", max_length=120),
        ),
    ]
