# Generated by Django 4.2.10 on 2024-02-25 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charge",
            name="paid",
        ),
        migrations.AddField(
            model_name="charge",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
