# Generated by Django 4.2.10 on 2024-02-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_remove_charge_paid_charge_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="charge",
            old_name="refunded",
            new_name="canceled",
        ),
        migrations.AddField(
            model_name="charge",
            name="cancellation_reason",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
