# Generated by Django 4.2.10 on 2024-02-25 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_rename_refunded_charge_canceled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charge",
            name="canceled",
        ),
        migrations.RemoveField(
            model_name="charge",
            name="cancellation_reason",
        ),
    ]
