# Generated by Django 4.2.10 on 2024-02-25 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_remove_charge_canceled_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="charge",
            name="outcome",
        ),
        migrations.RemoveField(
            model_name="charge",
            name="outcome_type",
        ),
        migrations.RemoveField(
            model_name="charge",
            name="risk_level",
        ),
        migrations.RemoveField(
            model_name="charge",
            name="seller_message",
        ),
    ]
