# Generated by Django 4.2.10 on 2026-09-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cart_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='source',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
    ]
