from decimal import Decimal

from django.core.management.base import BaseCommand
from django.db import transaction

from products.models import Category, Product
from tags.models import Tag


CATEGORIES = [
    ("Cabazes", "cabazes", "gift", 10),
    ("Cabazes de Natal", "natal", "star", 15),
    ("Conservas", "conservas", "tin", 20),
    ("Azeite & Vinagre", "azeite", "bottle", 30),
    ("Café", "cafe", "coffee", 40),
    ("Chá dos Açores", "cha", "leaf", 50),
    ("Mel & Doçaria", "mel", "jar", 60),
    ("Frutos Secos & Petiscos", "petiscos", "nut", 70),
    ("Sal & Especiarias", "sal", "salt", 80),
    ("Casa & Cortiça", "casa", "cork", 90),
]


def item(title, category, price, grammage, tags, description, featured=False, quantity=25):
    return {
        "title": title,
        "category": category,
        "price": price,
        "grammage": grammage,
        "tags": tags,
        "description": description,
        "featured": featured,
        "quantity": quantity,
    }


CATALOG = [
    item("Cabaz Sabores de Portugal - Taste of Portugal Hamper", "Cabazes", "48.00", "5 produtos",
         ["cabaz", "presente", "gift", "hamper", "azeite", "mel", "chá"],
         "The whole country in one box: DOP olive oil, lavender honey, Azores tea, flor de sal and a gourmet tin. Packed to travel as a gift.",
         featured=True, quantity=15),
    item("Cabaz Conservas Gourmet - Tinned Fish Gift Box", "Cabazes", "32.00", "4 latas",
         ["cabaz", "presente", "gift", "conservas", "fish", "sardinha"],
         "Four premium tins in a gift box: sardines, Azores tuna, mackerel and octopus. The easy present for anyone who loves the sea.",
         featured=True, quantity=15),
    item("Cabaz Café & Chá - Coffee and Tea Discovery Box", "Cabazes", "26.00", "4 produtos",
         ["cabaz", "presente", "gift", "café", "coffee", "chá", "tea"],
         "Specialty coffee, an espresso blend and two Azores teas. For the household split between the kettle and the machine.",
         featured=True, quantity=15),
    item("Cabaz Petisco Português - Portuguese Snack Box", "Cabazes", "29.00", "5 produtos",
         ["cabaz", "presente", "gift", "petisco", "snack", "azeitonas", "conservas"],
         "Everything for an evening petisco: tinned sardines, olives, roasted Algarve almonds, olive paté and chilli flakes.",
         quantity=15),
    item("Cabaz Pequeno-Almoço - Breakfast Hamper", "Cabazes", "34.00", "4 produtos",
         ["cabaz", "presente", "gift", "breakfast", "mel", "compota", "café"],
         "A slow Portuguese breakfast: heather honey, red berry jam, ground bica coffee and Azores black tea.",
         quantity=15),
    item("Duo Azeite & Flor de Sal - Olive Oil and Sea Salt Duo", "Cabazes", "22.00", "2 produtos",
         ["cabaz", "presente", "gift", "azeite", "flor de sal"],
         "A DOP extra virgin olive oil paired with hand-harvested Algarve flor de sal. A small gift that gets used every day.",
         quantity=20),

    item("Cabaz de Natal Clássico - Classic Christmas Hamper", "Cabazes de Natal", "59.00", "7 produtos",
         ["natal", "christmas", "cabaz", "presente", "gift"],
         "Olive oil, honey, quince paste, Azores tea, a gourmet tin, chocolate with flor de sal and roasted almonds, in a festive box.",
         featured=True, quantity=20),
    item("Cabaz de Natal Premium - Premium Christmas Hamper", "Cabazes de Natal", "89.00", "10 produtos",
         ["natal", "christmas", "cabaz", "presente", "gift", "premium"],
         "The generous version: early-harvest olive oil, tuna belly, eels in escabeche, São Jorge coffee, two honeys and a cork board.",
         featured=True, quantity=15),
    item("Cabaz de Natal Empresas - Corporate Christmas Hamper", "Cabazes de Natal", "45.00", "por unidade, mín. 10",
         ["natal", "christmas", "empresas", "corporate", "cabaz", "b2b"],
         "For teams and clients, from 10 boxes. Six Portuguese pantry favourites per box, a card with your message and delivery to one or many addresses.",
         featured=True, quantity=100),
    item("Lata Ilustrada de Natal - Illustrated Christmas Tin", "Cabazes de Natal", "18.00", "3 latas",
         ["natal", "christmas", "conservas", "presente", "gift"],
         "Three tins of sardines and mackerel in a limited Christmas illustrated sleeve. A stocking filler that is actually eaten.",
         quantity=30),
    item("Caixa de Chá de Natal - Christmas Tea Box", "Cabazes de Natal", "16.00", "3 x 50g",
         ["natal", "christmas", "chá", "tea", "açores", "presente"],
         "Black, green and lemon verbena teas from the Azores in a gift tin for the winter evenings.",
         quantity=30),

    item("Sardinhas em Azeite Extra Virgem - Sardines in Extra Virgin Olive Oil", "Conservas", "6.50", "120g",
         ["conserva", "sardinha", "azeite", "sem glúten"],
         "Whole sardines hand-packed in extra virgin olive oil, in the canning tradition of Matosinhos. Meaty and ready for toasted bread.",
         featured=True),
    item("Cavala em Azeite - Mackerel Fillets in Olive Oil", "Conservas", "5.20", "120g",
         ["conserva", "cavala", "azeite", "sem glúten"],
         "Tender mackerel fillets in olive oil. A lighter, affordable everyday tin with the same Atlantic character.",
         ),
    item("Atum dos Açores em Azeite - Azores Tuna in Olive Oil", "Conservas", "7.90", "120g",
         ["conserva", "atum", "açores", "pesca sustentável"],
         "Pole-and-line skipjack tuna from the Azores in olive oil. Firm, clean and a step above supermarket tuna.",
         featured=True),
    item("Ventresca de Atum - Tuna Belly in Olive Oil", "Conservas", "12.90", "110g",
         ["conserva", "atum", "ventresca", "premium"],
         "The prized belly cut of the tuna, silky and rich. Serve it cold with roasted peppers and good bread.",
         ),
    item("Filetes de Sardinha Picante - Spicy Sardine Fillets", "Conservas", "5.80", "120g",
         ["conserva", "sardinha", "picante", "piri-piri"],
         "Boneless sardine fillets with piri-piri, for anyone who likes some heat with their aperitivo.",
         ),
    item("Sardinhas com Limão - Sardines with Lemon", "Conservas", "6.20", "120g",
         ["conserva", "sardinha", "limão"],
         "Sardines in olive oil with a slice of lemon, bright and fresh-tasting straight from the tin.",
         ),
    item("Polvo em Azeite - Octopus in Olive Oil", "Conservas", "9.50", "120g",
         ["conserva", "polvo", "azeite"],
         "Cooked octopus in olive oil. Serve cold with lemon and coriander or warm over potatoes.",
         ),
    item("Lulas Recheadas - Stuffed Squid in Tomato Sauce", "Conservas", "8.40", "120g",
         ["conserva", "lulas", "tomate"],
         "Small squid stuffed and cooked in a tomato sauce, a full petisco in one tin.",
         ),
    item("Mexilhão em Escabeche - Mussels in Escabeche", "Conservas", "7.50", "110g",
         ["conserva", "mexilhão", "escabeche"],
         "Mussels in a light vinegar and olive oil escabeche with bay leaf. Great with a cold white wine.",
         ),
    item("Enguias de Escabeche - Eels in Escabeche from Aveiro", "Conservas", "11.50", "120g",
         ["conserva", "enguias", "aveiro", "escabeche"],
         "A specialty of the Aveiro lagoon: small eels fried and preserved in escabeche. An unusual, very local tin.",
         ),
    item("Filetes de Bacalhau em Azeite - Cod Fillets in Olive Oil", "Conservas", "9.90", "120g",
         ["conserva", "bacalhau", "cod", "azeite"],
         "Salt cod fillets in olive oil with garlic, ready for a quick salad with chickpeas.",
         ),
    item("Berbigão ao Natural - Cockles in Brine", "Conservas", "6.90", "110g",
         ["conserva", "berbigão", "marisco"],
         "Cockles from the Ria de Aveiro in brine, the base of a quick seafood rice.",
         ),
    item("Ovas de Sardinha - Sardine Roe in Olive Oil", "Conservas", "8.90", "110g",
         ["conserva", "ovas", "sardinha"],
         "A delicacy for the curious: sardine roe in olive oil, creamy and intense.",
         ),
    item("Paté de Sardinha - Sardine Paté", "Conservas", "3.90", "75g",
         ["conserva", "sardinha", "paté", "petisco"],
         "Smooth sardine paté for bread or crackers, the easiest way to bring tinned fish to guests.",
         ),

    item("Azeite Virgem Extra DOP Trás-os-Montes - DOP Extra Virgin Olive Oil", "Azeite & Vinagre", "12.90", "500ml",
         ["azeite", "dop", "trás-os-montes", "olive oil"],
         "Protected-origin extra virgin olive oil from Trás-os-Montes, cold pressed, with a peppery finish for dressing rather than frying.",
         featured=True),
    item("Azeite Virgem Extra do Alentejo - Alentejo Extra Virgin Olive Oil", "Azeite & Vinagre", "14.50", "750ml",
         ["azeite", "alentejo", "olive oil"],
         "Balanced and fruity Alentejo olive oil, the everyday bottle of a Portuguese kitchen.",
         ),
    item("Azeite Colheita Precoce - Early Harvest Olive Oil", "Azeite & Vinagre", "16.90", "500ml",
         ["azeite", "colheita precoce", "premium", "olive oil"],
         "Pressed from green olives at the start of the harvest: grassy, bitter-sweet and high in polyphenols.",
         ),
    item("Azeite Biológico - Organic Extra Virgin Olive Oil", "Azeite & Vinagre", "13.90", "500ml",
         ["azeite", "biológico", "organic", "vegan"],
         "Certified organic extra virgin olive oil from Portuguese groves.",
         ),
    item("Azeite com Piri-Piri - Piri-Piri Olive Oil", "Azeite & Vinagre", "9.50", "250ml",
         ["azeite", "piri-piri", "picante"],
         "Olive oil infused with piri-piri chilli, for grilled chicken, pizza and anything that needs a kick.",
         ),
    item("Azeite com Alho e Ervas - Garlic and Herb Olive Oil", "Azeite & Vinagre", "9.50", "250ml",
         ["azeite", "alho", "ervas"],
         "Olive oil with garlic, rosemary and oregano. Drizzle over bread, potatoes or grilled fish.",
         ),
    item("Vinagre de Vinho do Porto - Port Wine Vinegar", "Azeite & Vinagre", "8.50", "250ml",
         ["vinagre", "porto", "presente"],
         "Vinegar aged from Port wine, deep and slightly sweet. A few drops lift salads and roasted vegetables.",
         ),
    item("Vinagre de Moscatel - Moscatel Vinegar", "Azeite & Vinagre", "9.90", "250ml",
         ["vinagre", "moscatel", "setúbal"],
         "A fragrant, gently sweet vinegar made from Moscatel wine, lovely on fruit and goat cheese.",
         ),

    item("Café Torrado em Grão - Whole Bean Roast", "Café", "7.50", "250g",
         ["café", "grão", "coffee", "espresso"],
         "Classic Portuguese dark roast in whole beans: chocolatey, low in acidity and made for espresso.",
         ),
    item("Café Moído Lote Bica - Ground Espresso Blend", "Café", "6.90", "250g",
         ["café", "moído", "bica", "coffee"],
         "Ready-ground blend for the classic bica, arabica and robusta balanced for crema and body.",
         ),
    item("Café de Especialidade Microlote - Specialty Single Origin", "Café", "11.90", "250g",
         ["café", "especialidade", "coffee", "filter"],
         "A single-origin micro-lot roasted in Lisbon for filter and pour-over. Bright and floral.",
         ),
    item("Café de São Jorge Açores - Azores Island Coffee", "Café", "19.90", "100g",
         ["café", "açores", "são jorge", "raro", "coffee"],
         "Coffee grown on São Jorge island in the Azores, one of the few coffees grown in Europe. Tiny harvest, sweet and mild.",
         ),
    item("Café Lote Lisboa para Moka - Lisbon Moka Pot Blend", "Café", "7.90", "250g",
         ["café", "moka", "coffee"],
         "A medium grind for the stovetop moka pot, roasted a touch lighter for sweetness.",
         ),
    item("Café Descafeinado Moído - Ground Decaf", "Café", "7.20", "250g",
         ["café", "descafeinado", "decaf", "coffee"],
         "Water-process decaf with the body of a real bica, for the evening coffee.",
         ),
    item("Cápsulas Compostáveis - Compostable Coffee Capsules x10", "Café", "4.50", "10 un",
         ["café", "cápsulas", "compostável", "coffee"],
         "Nespresso-compatible capsules in a compostable shell.",
         ),

    item("Chá Preto Orange Pekoe dos Açores - Azores Black Tea", "Chá dos Açores", "6.90", "100g",
         ["chá", "preto", "açores", "tea"],
         "Black tea from São Miguel, one of the few tea plantations in Europe. Orange Pekoe grade, smooth and malty.",
         featured=True),
    item("Chá Verde Hysson dos Açores - Azores Green Tea", "Chá dos Açores", "7.40", "100g",
         ["chá", "verde", "açores", "tea"],
         "Azorean green tea grown in volcanic soil without pesticides. Grassy and clean.",
         ),
    item("Chá Preto Broken Leaf - Everyday Azores Black Tea", "Chá dos Açores", "5.90", "100g",
         ["chá", "preto", "açores", "tea"],
         "Broken-leaf black tea for a stronger, faster brew. The daily cup.",
         ),
    item("Chá Preto de Porto Formoso - Porto Formoso Black Tea", "Chá dos Açores", "7.20", "100g",
         ["chá", "preto", "açores", "porto formoso", "tea"],
         "From the other Azores tea estate, Porto Formoso. Rounder and lightly fruity.",
         ),
    item("Infusão de Lúcia-Lima - Lemon Verbena Infusion", "Chá dos Açores", "5.40", "50g",
         ["infusão", "lúcia-lima", "sem cafeína", "herbal"],
         "Caffeine-free lemon verbena, citrusy and calming after dinner.",
         ),
    item("Infusão de Cidreira & Limão - Lemon Balm and Lemon Infusion", "Chá dos Açores", "5.20", "50g",
         ["infusão", "cidreira", "sem cafeína", "herbal"],
         "Lemon balm with dried lemon peel, a gentle infusion for any time of day.",
         ),
    item("Infusão de Camomila - Chamomile Infusion", "Chá dos Açores", "4.90", "40g",
         ["infusão", "camomila", "sem cafeína", "herbal"],
         "Whole chamomile flowers for a soft, honeyed cup before bed.",
         ),
    item("Lata Presente Chá dos Açores - Azores Tea Gift Tin", "Chá dos Açores", "14.90", "2 x 100g",
         ["chá", "açores", "presente", "gift", "tea"],
         "Orange Pekoe and green tea from the Azores in a keepsake tin.",
         ),

    item("Mel de Rosmaninho DOP - Lavender Honey", "Mel & Doçaria", "9.90", "500g",
         ["mel", "dop", "rosmaninho", "honey"],
         "Protected-origin lavender honey from inland Portugal. Aromatic and slow to crystallise.",
         featured=True),
    item("Mel de Urze - Heather Honey", "Mel & Doçaria", "10.50", "500g",
         ["mel", "urze", "honey"],
         "Dark, malty heather honey from the northern mountains, rich in minerals.",
         ),
    item("Mel de Castanheiro - Chestnut Honey", "Mel & Doçaria", "10.90", "500g",
         ["mel", "castanheiro", "honey"],
         "Bold, slightly bitter chestnut honey, excellent with strong cheese.",
         ),
    item("Mel dos Açores - Azores Honey", "Mel & Doçaria", "11.90", "400g",
         ["mel", "açores", "honey"],
         "Light, floral honey from the Azores islands, gathered from incense tree blossom.",
         ),
    item("Compota de Frutos Vermelhos - Red Berry Jam", "Mel & Doçaria", "5.50", "280g",
         ["compota", "frutos vermelhos", "jam", "breakfast"],
         "Small-batch red berry jam with a high fruit ratio.",
         ),
    item("Compota de Figo - Fig Jam", "Mel & Doçaria", "5.80", "280g",
         ["compota", "figo", "jam", "algarve"],
         "Algarve figs cooked slowly into a thick jam. Perfect on a cheese board.",
         ),
    item("Doce de Abóbora com Noz - Pumpkin and Walnut Jam", "Mel & Doçaria", "5.20", "280g",
         ["doce", "abóbora", "noz", "tradicional"],
         "Traditional pumpkin jam with walnuts, a Portuguese pantry classic.",
         ),
    item("Doce de Tomate - Tomato Jam", "Mel & Doçaria", "5.20", "280g",
         ["doce", "tomate", "tradicional"],
         "Sweet tomato jam with cinnamon, surprising and very Portuguese. Try it with fresh cheese.",
         ),
    item("Marmelada Tradicional - Quince Paste", "Mel & Doçaria", "5.90", "250g",
         ["marmelada", "marmelo", "queijo", "tradicional"],
         "Firm quince paste, the original marmalade. Slice it onto a board with cured cheese.",
         ),
    item("Chocolate Negro com Flor de Sal - Dark Chocolate with Sea Salt", "Mel & Doçaria", "4.90", "100g",
         ["chocolate", "flor de sal", "doce"],
         "70 percent dark chocolate finished with Algarve flor de sal.",
         ),
    item("Bolachas de Manteiga Tradicionais - Traditional Butter Biscuits", "Mel & Doçaria", "4.50", "200g",
         ["bolachas", "biscuits", "doce", "tradicional"],
         "Crisp butter biscuits baked to an old family recipe, made for tea.",
         ),

    item("Amêndoa Torrada do Algarve - Roasted Algarve Almonds", "Frutos Secos & Petiscos", "7.90", "200g",
         ["amêndoa", "algarve", "frutos secos", "snack"],
         "Algarve almonds roasted with a pinch of salt. The classic companion to a glass of wine.",
         ),
    item("Figos Secos do Algarve - Dried Algarve Figs", "Frutos Secos & Petiscos", "6.50", "250g",
         ["figo", "algarve", "frutos secos"],
         "Sun-dried figs from the Algarve, soft and honey-sweet.",
         ),
    item("Amêndoas Cobertas - Sugar-Coated Almonds", "Frutos Secos & Petiscos", "5.90", "200g",
         ["amêndoa", "doce", "tradicional", "páscoa"],
         "Traditional sugar-coated almonds, the sweet of Portuguese Easter and weddings.",
         ),
    item("Azeitonas Galega em Salmoura - Galega Olives in Brine", "Frutos Secos & Petiscos", "4.90", "350g",
         ["azeitonas", "galega", "petisco", "olives"],
         "Small, intense Galega olives, the most Portuguese of olives, cured in brine with oregano.",
         ),
    item("Paté de Azeitona - Olive Paté", "Frutos Secos & Petiscos", "4.20", "100g",
         ["azeitonas", "paté", "petisco", "vegan"],
         "Black olive paté for bread and crackers.",
         ),
    item("Tremoços em Frasco - Lupini Beans in a Jar", "Frutos Secos & Petiscos", "3.50", "350g",
         ["tremoços", "petisco", "snack", "vegan"],
         "The beer snack of every Portuguese café, ready to eat.",
         ),
    item("Mistura de Frutos Secos - Mixed Nuts and Dried Fruit", "Frutos Secos & Petiscos", "6.90", "250g",
         ["frutos secos", "snack", "amêndoa", "figo"],
         "Almonds, walnuts, dried figs and raisins from Portuguese growers.",
         ),

    item("Flor de Sal do Algarve - Hand-Harvested Sea Salt Flower", "Sal & Especiarias", "5.90", "150g",
         ["sal", "flor de sal", "algarve", "vegan"],
         "Delicate salt crystals hand-skimmed from Algarve salt pans. A finishing salt.",
         featured=True),
    item("Flor de Sal com Ervas - Sea Salt Flower with Herbs", "Sal & Especiarias", "6.50", "150g",
         ["sal", "flor de sal", "ervas"],
         "Flor de sal with Mediterranean herbs for grilled fish, meat and vegetables.",
         ),
    item("Flor de Sal com Piri-Piri - Sea Salt Flower with Piri-Piri", "Sal & Especiarias", "6.50", "150g",
         ["sal", "flor de sal", "piri-piri", "picante"],
         "Flor de sal with a warm piri-piri kick.",
         ),
    item("Flor de Sal com Limão - Sea Salt Flower with Lemon", "Sal & Especiarias", "6.50", "150g",
         ["sal", "flor de sal", "limão"],
         "Flor de sal with dried lemon zest, made for fish and salads.",
         ),
    item("Piri-Piri em Flocos - Chilli Flakes", "Sal & Especiarias", "4.20", "45g",
         ["especiaria", "piri-piri", "picante", "vegan"],
         "Dried piri-piri flakes, the backbone of Portuguese heat.",
         ),
    item("Massa de Pimentão - Red Pepper Paste", "Sal & Especiarias", "4.90", "200g",
         ["massa de pimentão", "tempero", "tradicional"],
         "Sweet red pepper paste, the secret of Alentejo pork and roasts.",
         ),
    item("Colorau Doce - Sweet Paprika", "Sal & Especiarias", "3.90", "80g",
         ["colorau", "especiaria", "paprika"],
         "Sweet Portuguese paprika for stews, rice and chouriço dishes.",
         ),
    item("Tempero para Frango Piri-Piri - Piri-Piri Chicken Seasoning", "Sal & Especiarias", "4.50", "60g",
         ["tempero", "piri-piri", "frango"],
         "A ready blend of chilli, garlic, paprika and herbs for piri-piri chicken at home.",
         ),
    item("Pimenta Preta em Grão - Black Peppercorns", "Sal & Especiarias", "4.90", "80g",
         ["especiaria", "pimenta", "vegan"],
         "Whole black peppercorns for the mill.",
         ),

    item("Base de Tacho em Cortiça - Cork Trivet", "Casa & Cortiça", "12.90", "Ø 20 cm",
         ["cortiça", "cork", "casa", "presente"],
         "A thick natural cork trivet. Portugal produces about half of the world's cork.",
         ),
    item("Bases de Copo em Cortiça - Cork Coasters Set of 4", "Casa & Cortiça", "9.90", "4 un",
         ["cortiça", "cork", "casa", "presente"],
         "Four natural cork coasters with a tile-inspired print.",
         ),
    item("Tábua de Queijo em Cortiça - Cork and Wood Cheese Board", "Casa & Cortiça", "24.90", "30 x 20 cm",
         ["cortiça", "cork", "tábua", "presente", "gift"],
         "A wooden cheese board with a cork base, sized for a petisco for four.",
         ),
    item("Sabonete Artesanal de Lavanda - Handmade Lavender Soap", "Casa & Cortiça", "8.90", "150g",
         ["sabonete", "lavanda", "presente", "gift"],
         "Handmade soap with Portuguese lavender, wrapped in printed paper.",
         ),
    item("Azulejo Decorativo Pintado à Mão - Hand-Painted Tile", "Casa & Cortiça", "19.90", "15 x 15 cm",
         ["azulejo", "tile", "decoração", "presente", "gift"],
         "A hand-painted blue and white azulejo with a cork stand.",
         ),
    item("Avental de Linho - Linen Apron", "Casa & Cortiça", "22.90", "1 un",
         ["linho", "avental", "casa", "presente"],
         "A natural linen apron woven in the north of Portugal.",
         ),
    item("Íman Lata de Sardinha - Sardine Tin Magnet", "Casa & Cortiça", "4.90", "1 un",
         ["sardinha", "íman", "presente", "souvenir"],
         "A small illustrated sardine tin magnet for the fridge.",
         ),
]


class Command(BaseCommand):
    help = "Seed the catalog with Portuguese gourmet products for demand testing"

    def add_arguments(self, parser):
        parser.add_argument("--reset", action="store_true", help="Delete existing products, categories and tags first")

    @transaction.atomic
    def handle(self, *args, **options):
        if options["reset"]:
            Tag.objects.all().delete()
            Product.objects.all().delete()
            Category.objects.all().delete()
            self.stdout.write("Cleared products, categories and tags")

        categories = {}
        for name, slug, icon, ordering in CATEGORIES:
            obj, _ = Category.objects.get_or_create(name=name, defaults={"ordering": ordering, "slug": slug, "icon": icon})
            changed = False
            for field, value in (("ordering", ordering), ("slug", slug), ("icon", icon)):
                if getattr(obj, field) != value:
                    setattr(obj, field, value)
                    changed = True
            if changed:
                obj.save()
            categories[name] = obj

        created, updated = 0, 0
        for spec in CATALOG:
            fields = {
                "description": spec["description"],
                "price": Decimal(spec["price"]),
                "grammage": spec["grammage"],
                "category": categories[spec["category"]],
                "featured": spec["featured"],
                "active": True,
                "quantity": spec["quantity"],
            }
            product = Product.objects.filter(title=spec["title"]).first()
            if product:
                for key, value in fields.items():
                    setattr(product, key, value)
                product.save()
                updated += 1
            else:
                product = Product.objects.create(title=spec["title"], **fields)
                created += 1

            for tag_title in spec["tags"]:
                tag, _ = Tag.objects.get_or_create(title=tag_title)
                tag.products.add(product)

        self.stdout.write(self.style.SUCCESS(
            "Catalog ready: {created} created, {updated} updated, {cats} categories, {tags} tags".format(
                created=created, updated=updated, cats=Category.objects.count(), tags=Tag.objects.count()
            )
        ))
