# Generated by Django 4.2.10 on 2026-09-28 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_contactmessage_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitlistSignup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, default='', max_length=120)),
                ('occasion', models.CharField(blank=True, choices=[('family', 'Family or friends'), ('company', 'My company: team or clients'), ('self', 'For myself'), ('other', 'Something else')], default='', max_length=20)),
                ('company', models.CharField(blank=True, default='', max_length=120)),
                ('boxes', models.PositiveIntegerField(blank=True, null=True)),
                ('items', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('language', models.CharField(blank=True, default='', max_length=8)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
