# Generated by Django 4.2.10 on 2026-09-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_cart_source'),
        ('chats', '0004_waitlistsignup'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoorHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(blank=True, default='')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('source', models.CharField(blank=True, default='', max_length=40)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='door_hit', to='carts.cart')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
