# Generated by Django 4.2.10 on 2024-04-07 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_alter_order_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
    ]
