name: Unit tests

on:
  push:
    branches:
      - develop
  workflow_dispatch:
    branches:
      - develop

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Cache virtualenv
      uses: actions/cache@v3
      with:
        key: venv-${{ hashFiles('requirements.txt') }}
        path: venv
    - name: Install dependencies
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install -r requirements.txt
        echo "$VIRTUAL_ENV/bin" >> $GITHUB_PATH
        echo "VIRTUAL_ENV=$VIRTUAL_ENV" >> $GITHUB_ENV
    - name: Change Settings File for Tests
      run: echo "from .base_sqlite import *" > eCommerce_Django/settings/__init__.py
    - name: Run Tests
      run: python manage.py test --parallel=16 --keepdb --noinput
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        SUPPORT_EMAIL: ${{ secrets.SUPPORT_EMAIL }}
        EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
        MAILCHIMP_API_KEY: ${{ secrets.MAILCHIMP_API_KEY }}
        MAILCHIMP_EMAIL_LIST_ID: ${{ secrets.MAILCHIMP_EMAIL_LIST_ID }}
        MAILCHIMP_EMAIL_ADMIN: ${{ secrets.MAILCHIMP_EMAIL_ADMIN }}
        STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        STRIPE_PUB_KEY: ${{ secrets.STRIPE_PUB_KEY }}
        PAYPAL_BASE_URL: ${{ secrets.PAYPAL_BASE_URL }}
        PAYPAL_CLIENT_ID: ${{ secrets.PAYPAL_CLIENT_ID }}
        PAYPAL_CLIENT_SECRET: ${{ secrets.PAYPAL_CLIENT_SECRET }}
        HEROKU_DB_PASSWORD: ${{ secrets.HEROKU_DB_PASSWORD }}
