name: Unit tests

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9
    - name: Install Dependencies
      run: pip install -r requirements.txt
    - name: Run Tests
      run: python manage.py test
