# Generated by Django 4.2.10 on 2024-03-11 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_product_quantity_alter_product_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productfile",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="products.product"
            ),
        ),
    ]
