# Generated by Django 4.2.10 on 2024-03-22 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_productfile_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productfile",
            name="file",
        ),
    ]
