# Generated by Django 4.2.10 on 2024-04-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0006_category_product_category"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["ordering"],
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.AddField(
            model_name="category",
            name="ordering",
            field=models.IntegerField(default=0),
        ),
    ]
