# Generated by Django 4.2.10 on 2024-04-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0007_alter_category_options_category_ordering"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="grammage",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
