# Generated by Django 4.2.10 on 2026-09-28 10:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_category_icon_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_credit',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='image_license_url',
            field=models.URLField(blank=True, default='', max_length=300),
        ),
        migrations.AddField(
            model_name='product',
            name='image_source_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.CreateModel(
            name='BundleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundle_items', to='products.product')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_bundles', to='products.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
