# Generated by Django 4.2.10 on 2026-09-28 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_image_credit_product_image_license_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description_pt',
            field=models.TextField(blank=True, default=''),
        ),
    ]
